const MOD = 'PAGINATION'
export const UPDATE_PAGINATION = `${MOD}/UPDATE_PAGINATION`
export const RESET_PAGINATION = `${MOD}/RESET_PAGINATION`
export const GO_NEXT_PAGE = `${MOD}/GO_NEXT_PAGE`
export const GO_PREV_PAGE = `${MOD}/GO_PREV_PAGE`
export const GO_TO_PAGE = `${MOD}/GO_TO_PAGE`
export const APPEND_PAGE = `${MOD}/APPEND_PAGE`
