const MOD = 'CORE/LIST'
export const PREPEND = `${MOD}/PREPEND`
export const LAPPEND = `${MOD}/LAPPEND`
export const LSHIFT = `${MOD}/LSHIFT`
export const LPOP = `${MOD}/LPOP`
export const LSET = `${MOD}/LSET`
export const LREM = `${MOD}/LREM`
export const LREPLACE = `${MOD}/LREPLACE`
export const LTRIM = `${MOD}/LTRIM`
